"""
Streamlit App for Titanic Survival Prediction Filtering and Sorting
"""

import streamlit as st
from importlib import import_module
import pandas as pd
from prediction_utils import filter_by_pclass, filter_by_age_range, filter_by_gender, sort_by_survival_probability


st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Batch Explorer", "Real-Time Kafka Explorer"])


if page == "Batch Explorer":
    st.title("Titanic Survival Prediction Explorer")
    st.write("Filter and sort survival predictions by passenger class, age, and gender.")

    # Load predictions (assume results.csv is generated by main pipeline)
    results = pd.read_csv('titanic_ml/results.csv')

    # Sidebar filters
    # Handle one-hot encoded Pclass columns
    if 'Pclass' in results.columns:
        pclass_options = sorted(results['Pclass'].unique())
    else:
        # If one-hot encoded, infer possible classes
        pclass_options = [1]
        if 'Pclass_2' in results.columns:
            pclass_options.append(2)
        if 'Pclass_3' in results.columns:
            pclass_options.append(3)
    pclass = st.sidebar.selectbox("Passenger Class", options=pclass_options)
    # Use original Age for slider
    age_min = int(results['Age'].min())
    age_max = int(results['Age'].max())
    min_age, max_age = st.sidebar.slider("Age Range", age_min, age_max, (20, 30))

    # Use original Sex for gender selection
    # If encoded as 0/1, map to 'female'/'male'
    if set(results['Sex'].unique()) <= {0, 1}:
        gender_map = {0: 'female', 1: 'male'}
        gender_options = [gender_map[v] for v in sorted(results['Sex'].unique())]
        results['Sex_display'] = results['Sex'].map(gender_map)
        gender = st.sidebar.selectbox("Gender", options=gender_options)
    else:
        results['Sex_display'] = results['Sex']
        gender = st.sidebar.selectbox("Gender", options=results['Sex_display'].unique())
    sort_order = st.sidebar.selectbox("Sort by Survival Probability", options=["Descending", "Ascending"])
    ascending = sort_order == "Ascending"

    # Apply filters
    filtered = filter_by_pclass(results, pclass)
    filtered = filtered[(filtered['Age'] >= min_age) & (filtered['Age'] <= max_age)]
    filtered = filtered[filtered['Sex_display'] == gender]
    filtered = sort_by_survival_probability(filtered, ascending=ascending)

    # Show only original columns in the table
    display_cols = ['Name', 'Sex_display', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked', 'HasCabin', 'FamilySize', 'Title', 'Survival_Prob']
    display_cols = [col for col in display_cols if col in filtered.columns]
    # Convert Survival_Prob to percentage for display
    if 'Survival_Prob' in filtered.columns:
        filtered = filtered.copy()
        filtered['Survival_Prob (%)'] = (filtered['Survival_Prob'] * 100).round(1)
        display_cols = [col if col != 'Survival_Prob' else 'Survival_Prob (%)' for col in display_cols]
    st.write(f"Filtered Results ({len(filtered)} passengers):")
    st.dataframe(filtered[display_cols])
elif page == "Real-Time Kafka Explorer":
    kafka_realtime_app = import_module("kafka_realtime_app")
    kafka_realtime_app.run()

if __name__ == "__main__":
    pass
